# Generated by Django 4.2.2 on 2025-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version",
            field=models.BooleanField(verbose_name="Текущая версия"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(
                help_text="Введите номер версии...", verbose_name="Номер версии"
            ),
        ),
    ]
