# Generated by Django 4.2.2 on 2025-01-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "can_change_product_description",
                        "Может изменять описание продукта",
                    ),
                    (
                        "can_change_product_category",
                        "Может изменять категорию продукта",
                    ),
                    (
                        "can_change_product_status",
                        "Может изменять статус публикации продукта",
                    ),
                ],
                "verbose_name": "Продукт (Вешь?)",
                "verbose_name_plural": "Продукты (Вещи?)",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
